version: '3.3'
services:
  dbPostgres:
    env_file:
      - .env.development
    image: postgres
    restart: always
    ports:
      - 5432:5432
  dbPostgresTest:
    env_file:
      - .env.test
    image: postgres
    restart: always
    ports:
      - 5433:5432
